# Generated by Django 4.2.4 on 2023-09-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification',
            field=models.TextField(),
        ),
    ]
