# Generated by Django 4.2.4 on 2023-10-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_classification_usuarioid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='usuarioId',
            new_name='usuario',
        ),
    ]
